pashok:
  build: .
  volumes:
    - ./:/usr/src/app
  environment:
    LANG: en_US.UTF-8
    SLACK_TOKEN: YOUR_TOKEN
    TELEGRAM_TOKEN: YOUR_TOKEN
    TELEGRAM_TOKEN: YOUR_TOKEN
    TWITTER_ACCESS_SECRET: YOUR_TOKEN
    TWITTER_ACCESS_TOKEN: YOUR_TOKEN
    TWITTER_CONSUMER_KEY: YOUR_TOKEN
    TWITTER_CONSUMER_SECRET: YOUR_TOKEN
    GSE_API_KEY: YOUR_TOKEN
    GSE_CX: YOUR_TOKEN
