#!/bin/bash
echo "Trying to start kirpich..."
cd ${OPENSHIFT_REPO_DIR}
PID_FILE="${OPENSHIFT_DATA_DIR}kirpich.pid"
LOG_FILE="${OPENSHIFT_LOG_DIR}kirpich.log"
bundle exec ${OPENSHIFT_REPO_DIR}/bin/run --pid $PID_FILE --log $LOG_FILE -d
exit 0
